services:
  stats-server:
    build: ./stats-service
    image: ewm-stats-server
    container_name: ewm-stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stats_user
      - SPRING_DATASOURCE_PASSWORD=stats_password

  stats-db:
    image: postgres:16.1
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats_user
      - POSTGRES_PASSWORD=stats_password

  ewm-service:
    build: ./ewm-main-service
    image: ewm-main-service-placeholder
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=ewm_user
      - SPRING_DATASOURCE_PASSWORD=ewm_password
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:16.1
    container_name: ewm-main-db
    ports:
      - "6542:5432"
    volumes:
      - ./ewm-main-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./ewm-main-service/src/main/resources/distance.sql:/docker-entrypoint-initdb.d/2-distance.sql
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm_user
      - POSTGRES_PASSWORD=ewm_password